In [1]:
# import packages
import numpy as np
import pandas as pd

In [2]:
weather = pd.read_csv('complete_weather_data_1960-2018.csv')
weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20820 entries, 0 to 20819
Data columns (total 23 columns):
DATE                20820 non-null object
Precipitation       20819 non-null float64
Snowfall            18291 non-null float64
TMAX                20810 non-null float64
TMIN                20810 non-null float64
Fog                 7772 non-null float64
Heavy_fog           3384 non-null float64
Thunder             823 non-null float64
Ice_pellets         299 non-null float64
Hail                402 non-null float64
Glaze               663 non-null float64
Dust                46 non-null float64
Smoke               2852 non-null float64
Blowing             368 non-null float64
High_winds          12 non-null float64
Mist                2563 non-null float64
Drizzle             594 non-null float64
Freezing_dizzile    103 non-null float64
Rain                6578 non-null float64
Freezing            285 non-null float64
Snow                2759 non-null float64
Ice_Fog             265 non-null float64
Extreme             1 non-null float64
dtypes: float64(22), object(1)
memory usage: 3.7+ MB

In [3]:
# make date the index and check the head
weather.set_index('DATE', inplace=True)
weather.index = pd.to_datetime(weather.index)
weather.head()

,Precipitation,Snowfall,TMAX,TMIN,Fog,Heavy_fog,Thunder,Ice_pellets,Hail,Glaze,...,Blowing,High_winds,Mist,Drizzle,Freezing_dizzile,Rain,Freezing,Snow,Ice_Fog,Extreme
DATE,,,,,,,,,,,,,,,,,,,,,
1961-01-01,1.09,3.0,35.0,24.0,1.0,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN
1961-01-02,0.00,0.0,29.0,19.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1961-01-03,0.00,0.0,25.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1961-01-04,0.00,0.0,25.0,12.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1961-01-05,0.00,0.0,24.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# check the info
weather.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 20820 entries, 1961-01-01 to 2018-01-01
Data columns (total 22 columns):
Precipitation       20819 non-null float64
Snowfall            18291 non-null float64
TMAX                20810 non-null float64
TMIN                20810 non-null float64
Fog                 7772 non-null float64
Heavy_fog           3384 non-null float64
Thunder             823 non-null float64
Ice_pellets         299 non-null float64
Hail                402 non-null float64
Glaze               663 non-null float64
Dust                46 non-null float64
Smoke               2852 non-null float64
Blowing             368 non-null float64
High_winds          12 non-null float64
Mist                2563 non-null float64
Drizzle             594 non-null float64
Freezing_dizzile    103 non-null float64
Rain                6578 non-null float64
Freezing            285 non-null float64
Snow                2759 non-null float64
Ice_Fog             265 non-null float64
Extreme             1 non-null float64
dtypes: float64(22)
memory usage: 3.7 MB

In [5]:
# check # of empty values
weather.isnull().sum()

Precipitation           1
Snowfall             2529
TMAX                   10
TMIN                   10
Fog                 13048
Heavy_fog           17436
Thunder             19997
Ice_pellets         20521
Hail                20418
Glaze               20157
Dust                20774
Smoke               17968
Blowing             20452
High_winds          20808
Mist                18257
Drizzle             20226
Freezing_dizzile    20717
Rain                14242
Freezing            20535
Snow                18061
Ice_Fog             20555
Extreme             20819
dtype: int64

In [6]:
# we delete the rows for the data that missing too much
dropThis = pd.date_range('1978-04-01','1984-01-01')
weather = weather[~weather.index.isin(dropThis)]
weather.dropna(subset = ['Snowfall','TMAX','TMIN'])

,Precipitation,Snowfall,TMAX,TMIN,Fog,Heavy_fog,Thunder,Ice_pellets,Hail,Glaze,...,Blowing,High_winds,Mist,Drizzle,Freezing_dizzile,Rain,Freezing,Snow,Ice_Fog,Extreme
DATE,,,,,,,,,,,,,,,,,,,,,
1961-01-01,1.09,3.0,35.0,24.0,1.0,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN
1961-01-02,0.00,0.0,29.0,19.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1961-01-03,0.00,0.0,25.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1961-01-04,0.00,0.0,25.0,12.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1961-01-05,0.00,0.0,24.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-12-28,0.00,0.0,7.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-12-29,0.00,0.0,8.0,-3.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-12-30,0.06,0.6,13.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-12-31,0.00,0.0,10.0,-2.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01,0.00,0.0,8.0,-5.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# check the # of empty values
weather.isnull().sum()

Precipitation           1
Snowfall             2529
TMAX                   10
TMIN                   10
Fog                 10946
Heavy_fog           15334
Thunder             17895
Ice_pellets         18419
Hail                18316
Glaze               18055
Dust                18672
Smoke               15866
Blowing             18350
High_winds          18706
Mist                16155
Drizzle             18124
Freezing_dizzile    18615
Rain                12140
Freezing            18433
Snow                15959
Ice_Fog             18453
Extreme             18717
dtype: int64

In [8]:
# fill the blanks by 0 and check the data
weather.fillna(value = 0, inplace = True) 
weather.isnull().sum()

Precipitation       0
Snowfall            0
TMAX                0
TMIN                0
Fog                 0
Heavy_fog           0
Thunder             0
Ice_pellets         0
Hail                0
Glaze               0
Dust                0
Smoke               0
Blowing             0
High_winds          0
Mist                0
Drizzle             0
Freezing_dizzile    0
Rain                0
Freezing            0
Snow                0
Ice_Fog             0
Extreme             0
dtype: int64

In [9]:
# for extreme weather
def extreme(df):
    if df['Heavy_fog'] == 1 or df['Thunder'] == 1 or df['Hail'] == 1 or df['High_winds'] == 1 or df['Freezing'] == 1 or df['Snow'] == 1:
        return 1
    else: 
        return 0

SyntaxError: invalid syntax (<ipython-input-9-55fced0c15cf>, line 3)

In [ ]:
weather['Extreme'] = weather.apply(extreme, axis=1)

In [ ]:
# output it as a csv and then check it 
weather.to_csv('complete_weather_data_1960-2018_cleaned.csv')